---
parent: devops
serviceName: opensearch-k8s-operator
dockerFile: 'opensearch-operator/Dockerfile'
unitTests:
  command: cd opensearch-operator && make test
  platform: "linux/amd64,linux/arm64"
lint:
  command: cd opensearch-operator && make lint
